import SwiftUI

struct TermsView: View {
    let onAccept: () -> Void

    @State private var hasScrolledToBottom = false
    @State private var didAgree = false

    var body: some View {
        VStack(spacing: 0) {
            header
            Divider()
            scrollableTerms
            Divider()
            footer
        }
        .frame(width: 600, height: 560)
        .background(AppTheme.backgroundPrimary)
        .accessibilityElement(children: .contain)
        .accessibilityIdentifier("terms.root")
    }

    private var header: some View {
        VStack(spacing: 10) {
            ValeurLogoMark(size: 48)
            Text("Terms & Conditions")
                .font(AppTheme.headingFont(20, weight: .semibold))
                .foregroundStyle(AppTheme.textPrimary)
                .accessibilityIdentifier("terms.title")
            Text("Please read and accept the terms before using Valeur AI.")
                .font(AppTheme.uiFont(13))
                .foregroundStyle(AppTheme.textSecondary)
                .multilineTextAlignment(.center)
        }
        .padding(.top, 28)
        .padding(.bottom, 20)
        .padding(.horizontal, 36)
    }

    private var scrollableTerms: some View {
        ScrollView {
            Text(termsText)
                .font(AppTheme.uiFont(12.5))
                .foregroundStyle(AppTheme.textPrimary)
                .lineSpacing(4)
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(20)
                .background(
                    GeometryReader { geo in
                        Color.clear.preference(
                            key: BottomReachedKey.self,
                            value: geo.frame(in: .named("scroll")).maxY
                        )
                    }
                )
        }
        .coordinateSpace(name: "scroll")
        .background(AppTheme.surfacePrimary)
        .onPreferenceChange(BottomReachedKey.self) { maxY in
            if maxY <= 560 {
                hasScrolledToBottom = true
            }
        }
        .frame(maxHeight: .infinity)
    }

    private var footer: some View {
        VStack(spacing: 14) {
            Toggle(isOn: $didAgree) {
                Text("I have read and agree to the Terms & Conditions")
                    .font(AppTheme.uiFont(13))
                    .foregroundStyle(AppTheme.textPrimary)
            }
            .toggleStyle(.checkbox)
            .accessibilityIdentifier("terms.agreeCheckbox")

            HStack(spacing: 12) {
                Button("Decline") {
                    NSApplication.shared.terminate(nil)
                }
                .buttonStyle(.borderless)
                .font(AppTheme.uiFont(13))
                .foregroundStyle(AppTheme.textSecondary)

                Spacer()

                Button("Accept & Continue") {
                    onAccept()
                }
                .buttonStyle(AcceptButtonStyle())
                .disabled(!didAgree)
                .accessibilityIdentifier("terms.acceptButton")
            }
        }
        .padding(.horizontal, 24)
        .padding(.vertical, 18)
        .background(AppTheme.backgroundPrimary)
    }

    private var termsText: String {
        """
        Last updated: April 2025

        PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY BEFORE USING VALEUR AI.

        1. ACCEPTANCE OF TERMS

        By installing or using Valeur AI ("the App"), you agree to be bound by these Terms and Conditions. If you do not agree, do not use the App.

        2. DESCRIPTION OF THE APP

        Valeur AI is a macOS application that provides a unified interface for interacting with third-party AI services, including but not limited to OpenAI, Anthropic, Google Gemini, and OpenRouter ("AI Providers"). The App connects to these services using API keys that you supply.

        3. YOUR API KEYS AND THIRD-PARTY SERVICES

        You are solely responsible for obtaining valid API keys from AI Providers and for all usage and charges incurred through those keys. Your API keys are stored locally on your device using macOS Keychain. We do not transmit, collect, or store your API keys on any server.

        Your use of AI Provider services is governed by each provider's own terms of service and privacy policy. We are not responsible for the availability, accuracy, or content of responses generated by AI Providers.

        4. DATA AND PRIVACY

        All conversation data is stored locally on your device. Message content is encrypted at rest using AES-256-GCM. We do not collect, transmit, or have access to your conversation history or personal data.

        5. ACCEPTABLE USE

        You agree not to use the App to:
        • Generate, distribute, or promote unlawful, harmful, or abusive content.
        • Violate any applicable law or regulation.
        • Infringe upon the intellectual property rights of others.
        • Circumvent or violate the terms of service of any AI Provider.

        6. DISCLAIMER OF WARRANTIES

        THE APP IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE APP WILL BE ERROR-FREE, UNINTERRUPTED, OR FREE OF HARMFUL COMPONENTS.

        7. LIMITATION OF LIABILITY

        TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE APP.

        8. CHANGES TO TERMS

        We reserve the right to modify these Terms at any time. Continued use of the App after changes constitutes acceptance of the revised Terms.

        9. GOVERNING LAW

        These Terms are governed by applicable law. Any disputes shall be resolved in the appropriate jurisdiction.

        10. CONTACT

        For questions regarding these Terms, please contact us through the App's official channels.
        """
    }
}

private struct BottomReachedKey: PreferenceKey {
    static let defaultValue: CGFloat = 0
    static func reduce(value: inout CGFloat, nextValue: () -> CGFloat) {
        value = max(value, nextValue())
    }
}

private struct AcceptButtonStyle: ButtonStyle {
    @Environment(\.isEnabled) private var isEnabled

    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .font(AppTheme.uiFont(13, weight: .semibold))
            .foregroundStyle(.white)
            .padding(.horizontal, 18)
            .padding(.vertical, 7)
            .background(
                RoundedRectangle(cornerRadius: AppTheme.controlRadius, style: .continuous)
                    .fill(isEnabled ? AppTheme.accent : Color.secondary.opacity(0.4))
            )
            .opacity(configuration.isPressed ? 0.85 : 1)
            .animation(.easeOut(duration: 0.1), value: configuration.isPressed)
    }
}
